apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
  namespace: vault
spec:
  serviceName: consul
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - consul
              topologyKey: kubernetes.io/hostname
      containers:
        - name: consul
          image: "{{ image }}"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INITIAL_CLUSTER_SIZE
              value: "3"  # This should not change once consul has been created.
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul-gossip-secret
                  key: key
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=$(INITIAL_CLUSTER_SIZE)"
            - "-retry-join=consul-internal.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            - "-domain=consul."
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-config-file=/etc/consul/config/server.json"
            - "-server"
            - "-ui"
          ports:
            - containerPort: 8300
              name: server-rpc
            - containerPort: 8301
              name: serf-lan
            - containerPort: 8302
              name: serf-wan
            - containerPort: 8500
              name: http-api
            - containerPort: 8600
              name: dns-api
          volumeMounts:
            - name: consul-config
              mountPath: /etc/consul/config
            - name: consul-data
              mountPath: /consul/data
          readinessProbe:
            httpGet:
              path: /v1/operator/raft/configuration
              port: 8500
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: consul-config
          configMap:
            name: consul
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: consul
  namespace: vault
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: consul
